version: "2"

linters:
  default: none
  enable:
    - logcheck
  settings:
    custom:
      logcheck:
        type: "module"
        description: Checks log messages
        settings:
          loggers: ["slog", "zap"]
          patterns:
            - "(?i)pass(word)?|pwd"
            - "(?i)secret|private_key"
